# Global properties go here
spring:
   profiles:
      active: test
   main:
      allow-bean-definition-overriding: true
   datasource:
      # this maps to an in-memory database that lives within a single VM.
      # in case you want to use H2 with a file persistence or as a service
      # reference http://www.h2database.com/html/cheatSheet.html and
      # http://www.h2database.com/html/tutorial.html#using_server
      url: jdbc:h2:mem:testtest
      driver-class-name: org.h2.Driver
   jpa:
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5Dialect

mvc:
av:
   getAllPricesPath: /prices

# Set debug level logging for the Stock Price Client so that Feign requests and responses are logged out
log.level.org.galatea.starter.service.StockPriceClient: DEBUG
# Set info level logging for the autoconfigure package so that it doesn't print out the entire
# CONDITIONS EVALUATION REPORT on startup
logging.level.org.springframework.boot.autoconfigure: INFO

---
# Test properties go here
spring:
   profiles: test
   datasource:
      username: sa
      password:
   rest:
      # this points at the local WireMock server in the test environment.
      alphaVantageBasePath: http://localhost:${wiremock.server.port}/

---
# Dev properties go here
spring:
   profiles: dev
   datasource:
      username: sa
      password:
   rest:
      alphaVantageBasePath: https://www.alphavantage.co/query?
# set debug to get spring to log the classpath (and other things) on startup
debug: true

---
# UAT properties go here
spring:
   profiles: uat
   datasource:
      username: sa
      password:

---
